// const mypromise = new Promise((resolve, reject) =>{
// setTimeout(() =>{
//     resolve('foobar')
// },1000)

// })
// mypromise
// .then(value => {return value +  'what' })
// .then(value => { return value +  'is'})
// .then(value => {return value +  'your' })
// .then(value => {return value +  'name' })
// .then(value => { console.log(value)})
// .catch(err => {console.error(err)})

// const tpromise = new Promise((myResolvedPromise,myrejectedPromise) =>{
//     setTimeout(() =>{
//         myResolvedPromise(895)
//     },3000)

// })
// tpromise.then(value => {console.log('This is the output of the promise is ',value)})
// .catch(err => {console.error(err)})
// console.log('This is an asynchronous call')

